# Generated by Django 3.0.6 on 2020-10-23 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.IntegerField()),
                ('size', models.CharField(choices=[('S', 'small'), ('M', 'mediam'), ('L', 'large'), ('XL', 'Extra Large'), ('XXL', 'Ex Ex Large')], max_length=6)),
                ('tshirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Tshirt')),
            ],
        ),
    ]
