# Generated by Django 3.1.2 on 2020-10-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201026_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='slug',
            field=models.CharField(default=0, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
